matrix:
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
      ONLY_COMPILE="true"

script:
  -
    if [ "$ONLY_COMPILE" == "true" ]; then
      echo "Skipping deploy; just doing a build."
      exit 0;
    fi

after_success:
  - cd "$TRAVIS_BUILD_DIR"/docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m '

notifications:
  email: false

env:
  matrix:
    - filename='Lowercase.js'
    - filename='Title Case.js'
    - filename='Uppercase.js'
  global:
    - SOURCE_BRANCH=master
    - TARGET_BRANCH=gh-pages
