matrix:
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
      ONLY_COMPILE="true";
    fi

script:
  - if [ "$ONLY_COMPILE" == "true" ]; then
      echo "Skipping deploy; just doing a build.";
      exit 0;
    fi;
    REPO=`git config remote.origin.url`;
    SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:};
    git clone $REPO $TARGET_BRANCH;
    cd $TARGET_BRANCH;
    git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH;
    touch test.md;
    git config user.name "Travis CI";
    git config user.email "${GH_USER_EMAIL}";
    if [ -z `git diff --exit-code` ]; then
      echo "No changes to the output on this push; exiting.";
      exit 0;
    fi;
    git add .;
    git commit -m "Deploy to GitHub Pages:${TRAVIS_COMMIT}";
    git push -f -q https://${GH_USER}:${GH_API_KEY}@github.com/${TRAVIS_REPO_SLUG};

notifications:
  email: false

env:
  global:
    - SOURCE_BRANCH=master
    - TARGET_BRANCH=gh-pages
    - GH_USER=nalipaz
    - GH_USER_EMAIL='nicholas@alipaz.net'
