matrix:
  fast_finish: true

before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" -o "${TRAVIS_BRANCH}" != "${SOURCE_BRANCH}" ]; then
      ONLY_COMPILE="true";
    fi
  - REPO=`git config remote.origin.url`;
    SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:};
    git clone ${REPO} ${TARGET_BRANCH};
    cd ${TARGET_BRANCH};
    git checkout ${TARGET_BRANCH} || git checkout --orphan ${TARGET_BRANCH};
    git config user.name "Travis CI";
    git config user.email "${GH_USER_EMAIL}";

script:
  - if [ "${ONLY_COMPILE}" == "true" ]; then
      echo "Skipping deploy; just doing a build.";
      exit 0;
    fi;
  - if [ "${job}" == "first" ]; then
      printf "" > index.html;
    fi;
  - link="javascript:"$(echo $(cat ${TRAVIS_BUILD_DIR}/${name}.js | sed 's/^\s*\/\/.*?\n|([;\{\}])\s*\/\/.*?\n//'));
    printf "$(cat ${TRAVIS_BUILD_DIR}/templates/bookmarklet.html.tpl)\n"
     "${link}"
     "${title}"
     "${description}"
     >> index.html;
  - if [ "${job}" == "last" ]; then
      printf "$(cat ${TRAVIS_BUILD_DIR}/templates/index.html.tpl)"
       "$(cat ${TRAVIS_BUILD_DIR}/${TARGET_BRANCH}/index.html)"
       > index.html;
    fi;
  - if [ $(git status --porcelain | wc -l) -lt 1 ]; then
      echo "No changes to the output on this push; exiting.";
      exit 0;
    fi;

after_success:
  - git add .;
    git commit -m "Deploy to GitHub Pages:${TRAVIS_COMMIT}";
    git push -f -q https://${GH_USER}:${GH_API_KEY}@github.com/${TRAVIS_REPO_SLUG};

notifications:
  email: false

env:
  global:
    - SOURCE_BRANCH=master
    - TARGET_BRANCH=gh-pages
    - GH_USER=nalipaz
    - GH_USER_EMAIL='nicholas@alipaz.net'
  matrix:
    - name='lowercase' title='Lowercase'  description='Changes selected text in input or textarea to lowercase.' job='first'
    - name='titlecase' title='Title Case' description='Changes selected text in input or text area to Title Case.'
    - name='uppercase' title='Uppercase'  description='Changes selected text in input or text area to UPPERCASE.' job='last'
